version: "3.9"

services:

  redis:
    image: redis:7
    container_name: redis-ai-poet
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-poet-app
    depends_on:
      - redis
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      # Make sure the app talks to Redis by service name not localhost!
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    restart: unless-stopped

volumes:
  redis_data: